name: Simple Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
    strategy:
      matrix:
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        openssl_ref: [ 'master', 'openssl-3.5.0' ]
        debug: ['WOLFPROV_DEBUG=1', '']

  simple_test:
    name: Simple Test
    runs-on: ubuntu-22.04
    needs: build_wolfprovider
    timeout-minutes: 20
    strategy:
      matrix:
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        openssl_ref: [ 'master', 'openssl-3.5.0' ]
        force_fail: ['WOLFPROV_FORCE_FAIL=1', '']
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Retrieving wolfProvider from cache
        # Debug builds are not currently supported by build-wolfprovider.yml
        # so those are manually built as a separate step.
        if: ${{ matrix.debug == '' }}
        uses: actions/cache/restore@v4
        id: wolfprov-cache-restore
        with:
          path: |
            wolfssl-install
            wolfprov-install
            openssl-install/lib64
            openssl-install/include
            openssl-install/bin

          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Build wolfProvider
        if: ${{ matrix.debug != '' }}
        run: |
          ${{ matrix.debug }} \
            OPENSSL_TAG=${{ matrix.openssl_ref }} \
            WOLFSSL_TAG=${{ matrix.wolfssl_ref }} \
            ./scripts/build-wolfprovider.sh

      - name: Run simple tests
        run: |
          ${{ matrix.force_fail }} ./scripts/cmd_test/do-cmd-tests.sh
